// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace iosDemo
{
	public partial class iosDemoEntryController : UIViewController
	{
		public iosDemoEntryController (IntPtr handle) : base (handle)
		{
		}
	}
}
