// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Timesheet.Client.Shared.Features.Timesheets;

namespace iosDemo
{
	public partial class TimesheetView2Controller : UITableViewController
	{
		public TimesheetView2Controller (IntPtr handle) : base (handle)
		{
		}

		TimesheetResource _timesheet;

		TimesheetViewModel _vm;

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			_timesheet = Hub.GetEx<TimesheetResource> ("timesheet");
			_vm = new TimesheetViewModel ();
			_vm.InitialiseWith (_timesheet);
		}

		public override void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear (animated);
			this.timesheetName.Text = _timesheet.Name;
		}	
	}
}
